### ISSUE TITLE
Question: is the normal i3 (not i3-gaps) supported?

### ISSUE THREAD

**Issue by toku-sa-n** [moustacheful/glimmer#10]
### Versions
```
%i3 --version
i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors
```

I've downloaded the prebuilt glimmer 0.0.2 from the [release page](https://github.com/moustacheful/glimmer/releases/tag/v0.0.2).

### Problem
I'm using the normal i3, not i3-gaps. When I try to use glimmer, I get the following error.

```
%./glimmer --styles ~/git_repository/glimmer/themes/example.css 
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: Error("unknown variant `machine`, expected one of `title`, `instance`, `class`, `window_role`, `transient_for`", line: 1, column: 727) }', src/actors/i3_ipc.rs:74:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C
```

Is this error due to not using i3-gaps? If it is, can I submit a PR to replace all the occurrences of the word i3 with i3-gaps to remove the confusion?

### Reproduction
1. Download the binary
2. Run glimmer
3. Change the window focus by moving the mouse cursor.

(BTW, [i3-gaps is merged into i3](https://github.com/Airblader/i3) ([PR](https://github.com/i3/i3/pull/5241)). I think all the occurrences of i3-gaps should be replaced with "i3 with the gaps feature" or something.)

**Comment by moustacheful** [comment]
Hey again, sorry you've run into so many issues @toku-sa-n 

i3 or i3-gaps should work, it might be the newer version of i3 that may be causing issues. Could you try compiling this branch https://github.com/moustacheful/glimmer/pull/11 and let me know if works. 

Thanks!

**Comment by toku-sa-n** [comment]
It works! Thanks for the quick fix!
